export default {
    small: {
        width: "210px",
        iconContainerSize: "25px",
        bodyHeight: "225px",
        dateHeaderPaddingY: "5px",
        dateWeekItemSize: "20px",
        dateWeekItemSpace: "2.5px",
        dateListItemSize: "43.75px",
        dateListItemSpace: "0",
        hourItemSize: "45px",
        hourIconSize: "35px",
        hourItemFontSize: "13px",
        buttonsPadding: "0 20px 10px 10px",
        buttonMarginLeft: "5px" 
    },
    default: {
        width: "310px",
        spanMarginLeft: "9px",
        iconContainerSize: "40px",
        bodyHeight: "340px",
        dateHeaderPaddingY: "10px",
        dateWeekItemSize: "30px",
        dateWeekItemSpace: "5px",
        dateListItemSize: "60px",
        dateListItemSpace: "5px",
        hourItemSize: "60px",
        hourIconSize: "40px",
        hourItemFontSize: "20px",
        buttonsPadding: "0 25px 15px 15px",
        buttonMarginLeft: "10px" 
    },
    large: {
        width: "380px",
        iconContainerSize: "50px",
        bodyHeight: "340px",
        dateHeaderPaddingY: "10px",
        dateWeekItemSize: "30px",
        dateWeekItemSpace: "5px 10px",
        dateListItemSize: "60px",
        dateListItemSpace: "13.75px",
        hourItemSize: "60px",
        hourIconSize: "40px",
        hourItemFontSize: "20px",
        buttonsPadding: "0 30px 15px 15px",
        buttonMarginLeft: "10px" 
    },
    paddingX: "15px",
    paddingY: "10px",
    radius: "4px",
    fontSize: "14px",
    headerIconSize: "16px",
    dateHeaderIconSize: "20px",
    hourSpace: "10px"
}